apiVersion: v1
kind: Namespace
metadata:
  name: bcdr-cloudrock
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: bcdr-cloudrock-2v6br
  namespace: bcdr-cloudrock
spec:
  targetNamespaces:
  - bcdr-cloudrock
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/oadp-operator.bcdr-cloudrock: ''
  name: oadp-operator
  namespace: bcdr-cloudrock
spec:
  channel: stable
  installPlanApproval: Automatic
  name: oadp-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: oadp-operator.v0.5.6