---
apiVersion: cloudautomationmgr.ibm.com/v1alpha1
kind: Service
metadata:
  name: holiday-service-04
  namespace: default
spec:
  connection: aws_connect
  service:
    action: Provision
    instance_plan: standard
    name: HolidayShoppingService
    parameters:
      specifications:
        parameters:
          vm_name: holiday-service-04
          vm_desc: holiday-service-04
          Connection: aws_connect
          region: us-east-1
          vpc_name_tag: CAMVPC
          subnet_name: CAM
          public_ssh_key_name: holiday-service-04
          aws_image_size: t2.small
          aws_ami_owner_id: "099720109477"
          credential_name_suffix: holiday-service-04
          inventory_name: holiday-service-04
          cluster_name: holiday-service-04
          min_worker_count: 3
      templateParameters: []