---
apiVersion: cloudautomationmgr.ibm.com/v1alpha1
kind: Service
metadata:
  name: holiday-service-04
  namespace: default
spec:
  connection: aws_connect
  service:
    action: Provision
    instance_plan: standard
    name: HolidayShoppingService
    parameters:
      specifications:
        parameters:
          vm_name: holiday-service-04
          vm_desc: holiday-service-04
          Connection: aws_connect
          region: us-east-1
          vpc_name_tag: CAMVPC
          subnet_name: CAM
          public_ssh_key_name: holiday-service-04
          public_ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCpVR7Ah+8sd1SoEKJd75zOn3kKqaPJQ0GsbJ5cIaOPAnTuy1eJGRgMvFi1t0bvIkTPampVDGM8NYuLKJPqfocrJVL2GlG05rgWRmMUx5Kla+iMPKzbR7qD7QZN8ciT1auV0eDcV1R9n/1/eGUJSxElEQFOIU/0JytddH/PWoYYLyantUCJlU1zp4bIOXY/zAZZiHHikQSJ+zZuHX/w+PTdeNmmn09gC401b9O4ZZ35sJECDJnGTZduwJnwtajaZmqTQqZvedh25RrsPxBd2eyJNdFze9W40r12/9zk97zCdoSsU3Dw9V/szQm4Eh3xqQ6yoieumuDetSmWmnLfoizl root@exegetic1.fyre.ibm.com
          aws_image: ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*
          aws_image_size: t2.small
          aws_ami_owner_id: "099720109477"
          credential_name_suffix: holiday-service-04
          inventory_name: holiday-service-04
          cluster_name: holiday-service-04
          min_worker_count: 1
      templateParameters: []