apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: wordpress-catalog
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
spec:
  displayName: wordpress-operator
  publisher: ABC Inc.
  sourceType: grpc
  image: amitabhprasad/wordpress-operator-catalog:v0.0.1