apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wordpress
  annotations:
    argocd.argoproj.io/hook: sync
    argocd.argoproj.io/sync-wave: "110"
spec:
  path: /
  to:
    kind: Service
    name: wordpress
    weight: 100
  port:
    targetPort: 80