apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: wordpress-operator
  namespace: openshift-operators
  generateName: wordpress-subs
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "10"
spec:
  channel: alpha
  name: wordpress-operator
  source: wordpress-catalog
  sourceNamespace: openshift-operators
  installPlanApproval: Automatic
  startingCSV: wordpress-operator.v0.0.1