apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: wordpress-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: wordpress-operator
  source: wordpress-catalog
  sourceNamespace: openshift-operators
  installPlanApproval: Automatic
  startingCSV: wordpress-operator.v0.0.1