apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: wordpress-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  channel: alpha
  name: wordpress-operator
  source: wordpress-catalog
  sourceNamespace: argocd
  installPlanApproval: Automatic
  startingCSV: wordpress-operator.v0.0.1